/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Beginner's Run',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 100,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Jumping Hurdles',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 60,
      targetScore: 150,
      obstacleCount: 8,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Tricky Terrain',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.4,
      timeLimitSeconds: 90,
      targetScore: 200,
      obstacleCount: 10,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Obstacle Course',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 90,
      targetScore: 250,
      obstacleCount: 12,
      obstacleSpeed: 0,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'forest_clearing',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Treacherous Trail',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 120,
      targetScore: 300,
      obstacleCount: 15,
      obstacleSpeed: 0,
      collectibleCount: 30,
      collectibleValue: 10,
      backgroundTheme: 'forest_clearing',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Perilous Peaks',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 120,
      targetScore: 350,
      obstacleCount: 18,
      obstacleSpeed: 0,
      collectibleCount: 35,
      collectibleValue: 10,
      backgroundTheme: 'snowy_mountains',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Hazardous Highlands',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 150,
      targetScore: 400,
      obstacleCount: 20,
      obstacleSpeed: 0,
      collectibleCount: 40,
      collectibleValue: 10,
      backgroundTheme: 'snowy_mountains',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Daunting Descent',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 150,
      targetScore: 450,
      obstacleCount: 22,
      obstacleSpeed: 0,
      collectibleCount: 45,
      collectibleValue: 10,
      backgroundTheme: 'snowy_mountains',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Treacherous Traverse',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 180,
      targetScore: 500,
      obstacleCount: 25,
      obstacleSpeed: 0,
      collectibleCount: 50,
      collectibleValue: 10,
      backgroundTheme: 'snowy_mountains',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Pinnacle of Peril',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 180,
      targetScore: 550,
      obstacleCount: 28,
      obstacleSpeed: 0,
      collectibleCount: 55,
      collectibleValue: 10,
      backgroundTheme: 'snowy_mountains',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
